branch-defaults:
  default:
    environment: nursingadminapp-qa
global:
  application_name: nursing.adminapp.qa
  default_ec2_keyname: NursingUx
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running Docker 1.7.1
  default_region: us-east-1
  profile: eb-cli
  sc: null